### ISSUE TITLE
Difference between this and your RDP project?

### ISSUE THREAD

**Issue by ArticuNode** [jasonpang/screenshare#1]
Hi, I've been a big follower of some of your projects, its some pretty impressive work.
I was wondering though, what's the difference between this project and the RDP project you have?
Is this for WinRT perhaps or a Metro/Modern app version?  I would test it myself but I don't have Windows 8...

Thanks a lot, look forward to hearing back :)

**Comment by kishorviswanathan** [comment]
This one uses the new Desktop Duplication API which was implemented on Windows 8. It helps in getting screen data at a faster rate. The old method used a mirror driver which was slower. Only drawback is you will need a Windows version >= 8.

**Comment by ArticuNode** [comment]
Thanks for the update!  Just remembered this :) will give it a go later today since have now moved on to Windows 10.

Thanks again,
